server:
  port: 8002

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.199.100:3306/mySpringCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456

eureka:
  client:
    register-with-eureka: true  #是否将自己注册到 eureka server
    fetchRegistry: true  #是否抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true  #访问路径是否显示ip地址

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lzj.entity
