server:
  port: 8001

spring:
  application:
    name: hystrix-payment-service

eureka:
  client:
    register-with-eureka: true  #是否将自己注册到 eureka server
    fetchRegistry: true  #是否抓取已有的注册信息
    service-url:
      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/

