server:
  port: 80

spring:
  application:
    name: consul-order-service
    #consul注册中心
  cloud:
    consul:
      host: 192.168.199.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true  #开启心跳协议