server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true  #是否将自己注册到 eureka server
    fetchRegistry: true  #是否抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment80
    prefer-ip-address: true  #访问路径是否显示ip地址