server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由功能，以微服务名称进行路由
      routes:
        - id: pament_routh  #路由id没有固定规则，要求唯一
#          uri: http://localhost:8001  #匹配后提供服的务地址
          uri: lb://payment-service  #匹配后提供服的务地址
          predicates:
            - Path=/payment/myRibbon/**  #断言。路径匹配的进行路由
#            - After=2022-01-22T23:37:15.095+08:00[Asia/Shanghai]  #在某个时间之后才能路由
#            - Cookie=username,lzj  #带上cookie，并且名称为lzj才能路由
#            - Header=X-Request-Id,\d+  #请求头要有X-Request-Id属性，并且值为整数才能路由
#            - Query=username, \d+  #带username的参数并且值是整数才能路由
#          filters:
#            - AddRequestParameter=red, blue  #过滤器，参数必须有red并且值为blue才能通过

        - id: pament_routh2  #路由id没有固定规则，要求唯一
#          uri: http://localhost:8001  #匹配后提供服的务地址
          uri: lb://payment-service  #匹配后提供服的务地址
          predicates:
            - Path=/payment/discovery/**  #断言。路径匹配的进行路由
            - After=2022-01-22T23:37:15.095+08:00[Asia/Shanghai]  #在某个时间之后才能路由

eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true  #是否将自己注册到 eureka server
      fetch-registry: true  #是否抓取已有的注册信息
      defaultZone: http://eureka7001.com:7001/eureka/

