server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.199.100:3306/mySpringCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456

eureka:
  client:
    register-with-eureka: true  #是否将自己注册到 eureka server
    fetchRegistry: true  #是否抓取已有的注册信息
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
#      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径是否显示ip地址
    lease-renewal-interval-in-seconds: 1  #eureka客户端向服务端发送心跳的时间间隔，默认30秒
    lease-expiration-duration-in-seconds: 2  #eureka服务端收到最后一次心跳后等待时间上限，默认90秒，超时剔除服务

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lzj.entity
